### ISSUE TITLE
[C++] RSDK_ACTIVE_VAR is inconsistent with C

### ISSUE THREAD

**Issue by Jdsle** [RSDKModding/RSDKv5-GameAPI#16]
With C, you'd write it as:
```c
RSDK_ACTIVE_VAR(ObjectStruct, type);
```

WIth C++, you'd write it as:
```cpp
RSDK_ACTIVE_VAR(ObjectStruct::sVars, type);
RSDK_ACTIVE_VAR(sVars, type); // this works too
```

Object related defines in C++ usually just have you use the name of the object, rather than manually specifying sVars

**Comment by MegAmi24** [comment]
Fixing this would likely be a breaking change, which we don't want to deal with after your PR removed the `TYPE_BLANK` enum and gave us a bit of trouble.

**Comment by Jdsle** [comment]
thumbs up - totally my bad btw, changed it because it was inconsistent with the engine, no idea that it'd actually break anything
